replicaCount: 2
image:
  repository: "hello-world"
  tag: "v1.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000

# Scalability and Stability
replicaCount: 2
maxReplicaCount: 4

scalingMetrics:
  targetCPUUtilizationPercentage: 50

maxUnavailablePods: 25%

nodeSelector: {}

tolerations: []

affinity: {}

# Resources requirements
resources:
  requests:
    cpu: 200m
